name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *" 
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: strangercacaus
          outputs: dist/snake.svg?color_snake=#7c3aed&color_dots=#161B22,#0e4429,#006d32,#26a641,#39d353
          
      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4.0.0
        with:
          target_branch: output
          build_dir: dist
          keep_history: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
